import React, { useEffect, useState } from 'react';
import { Link } from "react-router-dom";
import axios from 'axios';
import jsPDF from 'jspdf';

function Users() {
    const [users, setUsers] = useState([]);

    useEffect(() => {
        axios.get('http://localhost:3001')
            .then(result => setUsers(result.data))
            .catch(err => console.log(err));
    }, []);

    const handleDelete = (id) => {
        axios.delete('http://localhost:3001/deleteUser/' + id)
            .then(res => {
                console.log(res);
                window.location.reload();
            })
            .catch(errr => console.log(errr));
    };

    const downloadRecordAsPDF = (user) => {
        const pdf = new jsPDF();

        // Add background color
        pdf.setFillColor("#fff");
        pdf.rect(0, 0, 110, 297, 'F'); // A4 page size

        // Add title
        pdf.setTextColor("#000000");
        pdf.setFontSize(18);
        pdf.text("Drugs Information", 105, 20, { align: 'center' });

        // Add user details
        pdf.setFontSize(12);
        pdf.text(`Code: ${user.code}`, 20, 40);
        pdf.text(`Name: ${user.name}`, 20, 60);
        pdf.text(`Unit Price: ${user.uprice}`, 20, 80);
        pdf.text(`Quantity: ${user.qty}`, 20, 100);
        pdf.text(`Expiry Date: ${user.expdate}`, 20, 120);

        // Add footer
        pdf.setTextColor("#808080");
        pdf.setFontSize(10);
        pdf.text("Generated by YourApp", 105, 280, { align: 'center' });

        pdf.save(`${user.name}.pdf`);
    };

    return (
        <div className="d-flex vh-100 justify-content-center align-items-center" style={{ backgroundColor: '#e9ecef' }}>
            <div className='w-90 rounded p-4' style={{ backgroundColor: '#fff' }}>
                <Link to='/Createuser' className="btn btn-primary">Add New Inventory Item</Link>
                <br /><br />
                <table className="table">
                    <thead>
                        <tr>
                            <th className="col">Drug Code</th>
                            <th className="col">Drug Name</th>
                            <th className="col">Unit Price</th>
                            <th className="col">Quantity</th>
                            <th className="col">Expiration Date</th>
                            <th className="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {users.map((user) => (
                            <tr key={user._id}>
                                <td>{user.code}</td>
                                <td>{user.name}</td>
                                <td>{user.uprice}</td>
                                <td>{user.qty}</td>
                                <td>{user.expdate}</td>
                                <td style={{ display: "flex", justifyContent: "space-between" }}>
    <Link to={`/update/${user._id}`} className="btn btn-primary">Update this record</Link>
    <button style={{ marginLeft: "10px" }} className="btn btn-danger" onClick={(e) => handleDelete(user._id)}>Delete this record</button>
    <button style={{ marginLeft: "10px" }} className="btn btn-success" onClick={() => downloadRecordAsPDF(user)}>Download as PDF</button>
</td>



                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

export default Users;
