import React, { useEffect, useState } from 'react';
import { Link } from "react-router-dom";
import axios from 'axios';
import jsPDF from 'jspdf';

function Users() {
    const [users, setUsers] = useState([]);
    const [searchTerm, setSearchTerm] = useState('');

    useEffect(() => {
        axios.get('http://localhost:3001/Users')
            .then(result => setUsers(result.data))
            .catch(err => console.log(err));
    }, []);

    const handleDelete = (id) => {
        axios.delete('http://localhost:3001/deleteUser/' + id)
            .then(res => {
                console.log(res);
                window.location.reload();
            })
            .catch(errr => console.log(errr));
    };

    const downloadRecordAsPDF = (user) => {
        const pdf = new jsPDF();

        // Add background color
        pdf.setFillColor("#fff");
        pdf.rect(0, 0, 110, 297, 'F'); // A4 page size

        // Add title
        pdf.setTextColor("#000000");
        pdf.setFontSize(18);
        pdf.text("Drugs Information - Inventory Report", 105, 20, { align: 'center' });

        // Add user details
        pdf.setFontSize(12);
        pdf.text(`Code: ${user.code}`, 20, 40);
        pdf.text(`Name: ${user.name}`, 20, 60);
        pdf.text(`Unit Price: ${user.uprice}`, 20, 80);
        pdf.text(`Quantity: ${user.qty}`, 20, 100);
        pdf.text(`Expiry Date: ${user.expdate}`, 20, 120);

        // Add footer
        pdf.setTextColor("#808080");
        pdf.setFontSize(10);
        pdf.text("Generated by Care central Inventory", 105, 280, { align: 'center' });

        pdf.save(`${user.name}.pdf`);
    };
    
    const filteredUsers = users.filter(user =>
        user.name.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return (
        <div className="d-flex vh-100 justify-content-center align-items-center" style={{ backgroundColor: '#A9A9A9' }}>
            <div className='w-90 rounded p-4' style={{ backgroundColor: '#e9ecef' }}>
                <Link to='/Createuser' className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h7 style={{ color: 'white' }}>Add New Drug Stocks</h7></Link>
                <br /><br />

                <input
                    type="text"
                    placeholder="Search by drug name"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    style={{
                        padding: '10px',
                        borderRadius: '5px',
                        border: '1px solid #ccc',
                        boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.1)',
                        width: '100%',
                        marginBottom: '10px' // Adjust this value to add spacing between the input field and the table
                    }}
                />
                <br></br><br></br>
                <table className="table table-striped">
                    <thead>
                        <tr>
                            <th className="col">Drug Code</th>
                            <th className="col">Drug Name</th>
                            <th className="col">Unit Price</th>
                            <th className="col">Quantity</th>
                            <th className="col">Expiration Date</th>
                            <th className="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {filteredUsers.map((user) => (
                            <tr key={user._id}>
                            
                                <td>{user.code}</td>
                                <td>{user.name}</td>
                                <td>{user.uprice}</td>
                                <td>{user.qty}</td>
                                <td>{user.expdate}</td>

                                <td style={{ display: "flex", justifyContent: "space-between" }}>
    <Link to={`/update/${user._id}`} className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h7 style={{ color: 'white' }}>Update</h7></Link>
    <button style={{ marginLeft: "10px" }} className="btn btn-danger" onClick={(e) => handleDelete(user._id)}>Delete</button>
    <button style={{ marginLeft: "10px" ,backgroundColor: '#001f3f'}} className="btn btn-light" onClick={() => downloadRecordAsPDF(user)}><h7 style={{ color: 'white' }}>Download as PDF</h7></button>
   
</td>



                            </tr>
                        ))}
                    </tbody>
                   
                    
                </table>
            </div>
        </div>
    );
}

export default Users;
