import React, { useEffect, useState } from 'react';
import { Link } from "react-router-dom";
import axios from 'axios';
import jsPDF from 'jspdf';


function Infos() {
    const [infos,setInfos] = useState([]);
    const [searchQuery, setSearchQuery] = useState('');
    

    useEffect(() => {
        axios.get('http://localhost:3001/Info')
            .then(result => setInfos(result.data))
            .catch(err => console.log(err));
    }, []);

   

    const handleDelete = (id) => {
        axios.delete('http://localhost:3001/deleteInfo/' + id)
            .then(res => {
                console.log(res);
                window.location.reload();
            })
            .catch(errr => console.log(errr));
    };

    const downloadRecordAsPDF = (info) => {
        const pdf = new jsPDF();

        // Add background color
        pdf.setFillColor("#fff");
        pdf.rect(0, 0, 110, 297, 'F'); // A4 page size

        // Add title
        pdf.setTextColor("#000000");
        pdf.setFontSize(18);
        pdf.setFontSize(11);
        pdf.text("Bank Details of suppliers - Inventory Report", 105, 20, { align: 'center' });
        pdf.text("Unauthorized disclosure, distribution, or copying of this report, in whole or in part, is strictly prohibited", 105, 40, { align: 'center'});

        // Add user details
        pdf.setFontSize(12);
        pdf.text(`Supplier ID : ${info.sbid}`, 20, 70);
        pdf.text(`Bank : ${info.bank}`, 20, 90);
        pdf.text(`Account Number: ${info.accno}`, 20, 110);
        pdf.text(`Account Holder's Name: ${info.accname}`, 20, 130);
        pdf.text(`Branch : ${info.branch}`, 20, 150);

        // Add footer
        pdf.setTextColor("#FF0000");
        pdf.setFontSize(10);
        pdf.text("Generated by Care Central Inventory", 105, 280, { align: 'center' });

        pdf.save(`${info.name}.pdf`);
    };

    const filteredInfos = infos.filter(info =>
        info.sbid.toLowerCase().includes(searchQuery.toLowerCase())
    );

return (
    <div className="d-flex vh-100 justify-content-center align-items-center" style={{ backgroundColor: '#A9A9A9client' }}>
    <div className='w-90 rounded p-4' style={{ backgroundColor: '#e9ecef' }}>
           <Link to="/CreateInfo" className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h7 style={{ color: 'white' }}>Add Entry</h7></Link>
        
           <br></br><br></br>

           <input
                    type="text"
                    placeholder="Search by supplier ID"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    style={{
                        padding: '10px',
                        borderRadius: '5px',
                        border: '1px solid #ccc',
                        boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.1)',
                        width: '100%',
                        marginBottom: '10px' // Adjust this value to add spacing between the input field and the table
                    }}
                />

                <br></br><br></br>
            <table className="table table-striped">
                <thead>
                   <tr>
                        <th className="col">Supplier ID</th>
                        <th className="col">Bank</th>
                        <th className="col">Account Number</th>
                        <th className="col">Account Holder's Name</th>
                        <th className="col">Branch</th>
                        <th className="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {filteredInfos.map((info) => (
                        <tr key={info._id}>
                            <td>{info.sbid}</td>
                            <td>{info.bank}</td>
                            <td>{info.accno}</td>
                            <td>{info.accname}</td>
                            <td>{info.branch}</td>
                            <td>
                            <Link to={`/updateInfo/${info._id}`} className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h7 style={{ color: 'white' }}>Update</h7></Link>
                                <button style={{ marginLeft: "10px" }} className='btn btn-danger' onClick={(e) => handleDelete(info._id)}>Delete</button>
                                <button style={{ marginLeft: "10px" , backgroundColor: '#001f3f' }} className="btn btn-light" onClick={() => downloadRecordAsPDF(info)}><h7 style={{ color: 'white' }}>Download as a PDF</h7></button>
                               
                               
                            </td>



                        </tr>
                    ))}
                </tbody>
                
            </table>
            
        </div>
        
    </div>


    
)


}

export default Infos;



