import React, { useEffect, useState } from 'react';
import { Link } from "react-router-dom";
import axios from 'axios';
import jsPDF from 'jspdf';

function Suppliers() {
    const [suppliers, setSuppliers] = useState([]);
    const [searchQuery, setSearchQuery] = useState('');
    const [currentTime, setCurrentTime] = useState('');

    useEffect(() => {
        axios.get('http://localhost:3001/Suppliers')
            .then(result => setSuppliers(result.data))
            .catch(err => console.log(err));

            const intervalId = setInterval(() => {
                const now = new Date();
                setCurrentTime(now.toLocaleString());
            }, 1000);
    
            return () => clearInterval(intervalId);
    }, []);

    

    const handleDelete = (id) => {
        axios.delete('http://localhost:3001/deleteSupplier/' + id)
            .then(res => {
                console.log(res);
                window.location.reload();
            })
            .catch(errr => console.log(errr));
    };

    const downloadRecordAsPDF = (supplier) => {
        const pdf = new jsPDF();

        // Add background color
        pdf.setFillColor("#fff");
        pdf.rect(0, 0, 110, 297, 'F'); // A4 page size

        // Add title
        pdf.setTextColor("#000000");
        pdf.setFontSize(18);
        pdf.setFontSize(11);
        pdf.text("Bank Details of suppliers - Inventory Report", 105, 20, { align: 'center' });
        pdf.text("Unauthorized disclosure, distribution, or copying of this report, in whole or in part, is strictly prohibited", 105, 40, { align: 'center'});

        // Add user details
        pdf.setFontSize(12);
        pdf.text(`Supplier ID : ${supplier.sid}`, 20, 70);
        pdf.text(`Bank : ${supplier.name}`, 20, 90);
        pdf.text(`Account Number: ${supplier.address}`, 20, 110);
        pdf.text(`Account Holder's Name: ${supplier.district}`, 20, 130);
        pdf.text(`Branch : ${supplier.email}`, 20, 150);
        pdf.text(`Branch : ${supplier.contact}`, 20, 170);

        // Add footer
        pdf.setTextColor("#FF0000");
        pdf.setFontSize(10);
        pdf.text("Generated by Care Central Inventory", 105, 280, { align: 'center' });

        pdf.save(`${supplier.name}.pdf`);
    };

    // Filter suppliers based on search query
    const filteredSuppliers = suppliers.filter(supplier =>
        supplier.name.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (

         

        <div className="d-flex vh-100 justify-content-center align-items-center" style={{ background: 'linear-gradient(to top, white, navy)' }}>
    
            <div className='w-90 rounded p-4' style={{ background: 'linear-gradient(to top, navy, white)'}}>
               
                <Link to="/Createsupplier" className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h7 style={{ color: 'white' }}>Add Entry</h7></Link>
                
                <br/><br/>
                {/* Search Input */}
                <input
                    type="text"
                    placeholder="Search by supplier name"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    style={{
                        padding: '10px',
                        borderRadius: '5px',
                        border: '1px solid #ccc',
                        boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.1)',
                        width: '100%',
                        marginBottom: '10px'
                    }}
                /><br></br><br></br>

<center><div style={{ backgroundColor: 'lavender', padding: '10px', borderRadius: '10px' }}>
    <p style={{ color: 'green', margin: '0', fontWeight: 'bold', fontStyle: 'italic' }}>
        Total Record Count: <h1><b>{filteredSuppliers.length}</b></h1>
        </p>
  
        <h3 style={{ background: 'linear-gradient(to bottom, papayawhip, white)' , fontWeight:'bold'}}>{currentTime} - Care Central - Supplier Management</h3>
     
    </div></center>


                 <br></br>

              <h6>  <table className="table table-striped">
                    <thead>
                        <tr>
                            <th className="col">Supplier ID</th>
                            <th className="col">Supplier Name</th>
                            <th className="col">Address</th>
                            <th className="col">District</th>
                            <th className="col">Email</th>
                            <th className="col">Contact</th>
                           
                            <th className="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {filteredSuppliers.map((supplier) => (
                            <tr key={supplier._id}>
                                <td>{supplier.sid}</td>
                                <td>{supplier.name}</td>
                                <td>{supplier.address}</td>
                                <td>{supplier.district}</td>
                                <td>{supplier.email}</td>
                                <td>{supplier.contact}</td>
                        
                                <td style={{ display: "flex", justifyContent: "space-between" }}>
                                    <Link to={`/UpdateDeleteSupplier/${supplier._id}`} className='btn btn-light rounded-2' style={{ backgroundColor: '#001f3f'}}><h7 style={{ color: 'white' }}>Update</h7></Link>
                                    <button style={{ marginLeft: "10px" }} className='btn btn-danger' onClick={(e) => handleDelete(supplier._id)}>Delete</button>
                                    <button style={{ marginLeft: "10px", backgroundColor: '#001f3f' }} className="btn btn-light" onClick={() => downloadRecordAsPDF(supplier)}><h7 style={{ color: 'white' }}>Download</h7></button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table></h6>
            </div>
        </div>
    );
}

export default Suppliers;
